### ISSUE TITLE
Порт на android

### ISSUE THREAD

**Issue by mishailovic** [SsNiPeR1/libzxc#1]
Здравствуйте, очень хотелось бы видеть порт на такую операционную систему как android. Программа очень нужная но не всегда есть компьютер под рукой

**Comment by SsNiPeR1** [comment]
> Здравствуйте, очень хотелось бы видеть порт на такую операционную систему как android. Программа очень нужная но не всегда есть компьютер под рукой

так статические библиотеки и на андроиде работают как бы
